[changelog]
header = "# Changelog\n\nAll notable changes to this project will be documented in this file.\n"
body = """
{% if version %}\n## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}\n{% else %}\n## [unreleased]\n{% endif %}\n
{% for group, commits in commits | group_by(attribute="group") %}
  ### {{ group | upper_first }}
  {% for commit in commits %}
    - {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}{% if commit.scope %} _({{ commit.scope }})_{% endif %}
  {% endfor %}
{% endfor %}\n
{% if previous %}\n  {% if version %}\n    [{{ version }}]: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ previous.version }}...{{ version }}\n  {% endif %}\n{% endif %}\n"""
trim = true
postprocess = ""

[git]
conventional_commits = true
commit_preprocessors = [
  { pattern = '\s+', replace = " " },
]
filter_unconventional = true
split_commits = false
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactor" },
  { message = "^style", group = "Styling" },
  { message = "^test", group = "Testing" },
  { message = "^docs", group = "Documentation" },
  { message = "^chore", group = "Miscellaneous" },
  { message = "^ci", group = "Continuous Integration" },
  { message = "^build", group = "Build" },
  { message = "^revert", group = "Revert" },
]
protect_breaking_commits = true
filter_commits = false
sort_commits = "newest"
