// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "localhost:8080/" | (string & {})
}

export type MainHealthStatus = {
  db_connected?: boolean
  last_call?: string
  total_stations?: number
}

export type GetApiHealthData = {
  body?: never
  path?: never
  query?: never
  url: "/api/health"
}

export type GetApiHealthErrors = {
  /**
   * Internal Server Error
   */
  500: {
    [key: string]: string
  }
}

export type GetApiHealthError = GetApiHealthErrors[keyof GetApiHealthErrors]

export type GetApiHealthResponses = {
  /**
   * OK
   */
  200: MainHealthStatus
}

export type GetApiHealthResponse =
  GetApiHealthResponses[keyof GetApiHealthResponses]
